### ISSUE TITLE
Undefined function 'edison_wrapper' for input arguments of type 'function_handle'.

### ISSUE THREAD

**Issue by ashishnimrot** [kittenish/Shadow-Detection-and-Removal#3]
>> main
Warning: Name is nonexistent or not a directory: libsvm 
> In path at 110
  In addpath at 87
  In main at 2 
Warning: Name is nonexistent or not a directory: .\libsvm\matlab 
> In path at 110
  In addpath at 87
  In main at 3 
Segmenting
Undefined function 'edison_wrapper' for input arguments of type 'function_handle'.

Error in detect (line 17)
    [dummy seg] = edison_wrapper(im, @RGB2Luv, ...

Error in main (line 22)
[seg, segnum, between, near, centroids, label, grad, texthist] = detect(url);

**Comment by sunbin1205** [comment]
@ashishnimrot   hi，i had the same error as yours,have you solve the question?Undefined function 'edison_wrapper' for input arguments of type 'function_handle'.

**Comment by kittenish** [comment]
The error you got is from the segmenting part, where I used the _meanshift_ method. Please download the library and compile it on your own machine.

**Comment by sunbin1205** [comment]
Thank you for your reply. The problem has been solved!


------------------ 原始邮件 ------------------
发件人: "Jiarui Gao"<notifications@github.com>;
发送时间: 2018年11月8日(星期四) 凌晨4:10
收件人: "kittenish/Image-Shadow-Detection-and-Removal"<Image-Shadow-Detection-and-Removal@noreply.github.com>;
抄送: "SUN"<1445673818@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [kittenish/Image-Shadow-Detection-and-Removal] Undefined function'edison_wrapper' for input arguments of type 'function_handle'. (#3)




The error you got is from the segmenting part, where I used the meanshift method. Please download the library and compile it on your own machine.

**Comment by Naren3361** [comment]
> The error you got is from the segmenting part, where I used the _meanshift_ method. Please download the library and compile it on your own machine.

What's the library it is

**Comment by Naren3361** [comment]
What's the library to be included

**Comment by SorourMo** [comment]
I've used [this wrapper](https://github.com/mpizenberg/meanshift_edison_matlab_interface) (cloning all of its files) and added the downloaded directory path at the beginning of main.m. It worked for me.
